// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    Canmore.archie = new Canmore.Architect("http://glowing-moon-5208.heroku.com/");
    return AR.context.onLocationChanged = function(lat, long, alt, acc) {
      return Canmore.archie.locationChanged(lat, long, alt, acc);
    };
  });

}).call(this);
